// Admin Pages - Main Exports
export { Categories } from './categories/Categories';
export { Customers } from './customers/Customers';
export { Dashboard } from './dashboard/Dashboard';
export { ProductCatalog } from './productCatalog/ProductCatalog';
export { ProductsManagement } from './productsManagement/ProductsManagement';
export { Purchases } from './purchases/Purchases';
export { Reports } from './reports/Reports';
export { Roles } from './roles/Roles';
export { Sales } from './sales/Sales';
export { Suppliers } from './suppliers/Suppliers';
export { Users } from './users/Users';
